//! pre-view camera data for the ray tracing passes.
use bevy::{
    prelude::*,
    render::{
        Render, RenderApp, RenderSystems,
        camera::ExtractedCamera,
        render_resource::{ShaderType, UniformBuffer},
        renderer::{RenderDevice, RenderQueue},
        view::ExtractedView,
    },
};

/// gpu mirror of the camera a tracing pass runs for.
///
/// everything is world space. rays are generated by inverting the engine's own
/// projection
#[derive(Clone, Copy, Debug, Default, ShaderType)]
#[repr(C)]
pub struct ShineCameraUniform {
    /// inverse of `clip_from_view * view_from_world`, so `w = 1` unprojects.
    pub world_from_clip: Mat4,

    pub camera_position: Vec4,

    pub viewport: UVec4,
}

/// the camera uniform of one view, uploaded every frame.
#[derive(Component)]
pub struct ShineCamera(pub UniformBuffer<ShineCameraUniform>);

/// uploads one [`ShineCameraUniform`] per view
pub fn prepare_shine_cameras(
    mut commands: Commands,
    render_device: Res<RenderDevice>,
    render_queue: Res<RenderQueue>,
    views: Query<(Entity, &ExtractedView, &ExtractedCamera)>,
) {
    for (entity, view, camera) in &views {
        if camera.physical_target_size.is_none() {
            continue;
        }
        let view_from_world = view.world_from_view.to_matrix().inverse();
        let world_from_clip = (view.clip_from_view * view_from_world).inverse();

        let mut uniform = UniformBuffer::from(ShineCameraUniform {
            world_from_clip,
            camera_position: view.world_from_view.translation().extend(0.0),
            viewport: view.viewport,
        });

        uniform.write_buffer(&render_device, &render_queue);

        commands.entity(entity).insert(ShineCamera(uniform));
    }
}

pub struct CameraPlugin;
impl Plugin for CameraPlugin {
    fn build(&self, app: &mut App) {
        let Some(render_app) = app.get_sub_app_mut(RenderApp) else {
            return;
        };

        render_app.add_systems(
            Render,
            prepare_shine_cameras.in_set(RenderSystems::PrepareResources),
        );
    }
}
