[package]
name = "modular_character"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { path = "../../bevy_0.15/", features = ["wayland", "dynamic_linking"] }
bevy_asset_loader = "0.22.0"
bevy_panorbit_camera = "0.25.0"

# outdated
bevy_mod_billboard = "0.7.0"
