[package]
name = "modular_character"
version = "0.1.0"
edition = "2021"

[features]
with-inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = { path = "../../bevy_0.15/", features = ["wayland", "dynamic_linking"] }
paste = "1.0"
bevy-inspector-egui = { version = "0.28.1", optional = true }
