[package]
name = "bevy_shine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { path = "../../bevy_engines/bevy_0.16/", features = ["wayland", "dynamic_linking"] }
bytemuck = "1.23.0"
itertools = "0.14.0"
