[package]
name = "bevy_shine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { path = "../../bevy_engines/bevy_0.16/", features = ["wayland", "dynamic_linking"] }
bvh = { version = "0.10.0" }
bytemuck = { version = "1.21.0", features = ["derive"] }
itertools = "0.13.0"
