[package]
name = "bevy_shine"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.0-rc.1", features = ["bevy_solari"] }
bytemuck = "1.23.0"
radsort = "0.1"
itertools = "0.14.0"
