[package]
name = "bevy_shine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy_asset_loader = { version = "0.22.0", git = "https://github.com/NiklasEi/bevy_asset_loader", branch = "bevy-0-15" }
