* bevy_shine
  My interest in high-quality rendering, particularly real-time ray tracing, led me to develop bevy_shine. This project is a ray tracing plugin I created for the Bevy engine to further my understanding of its implementation.
** Intro
   bevy_shine is a GI plugin based on wgpu's hardware ray tracing capabilities. It draws inspiration from solari, bevy's built-in ray tracing plugin.
* Reference
** bevy_hikari
   https://github.com/cryscan/bevy-hikari

   本项目受bevy_hikari启发，做为学习光线追踪并为bevy高版本重新制作
** 《Ray Tracing in One Weekend》
   https://raytracing.github.io/

   在开始本项目前，我学习了《Ray Tracing in One Weedkend》系列三本书藉，按照参考代码实现了书中的示例
** 《Ray Tracing Gems II》
   http://raytracinggems.com/

   学习过程中大量参考《Ray Tracing Gems II》
** Some GI data
   SDFGI (SDF + probe based): https://www.docdroid.net/YNntL0e/godot-sdfgi-pdf
   GI-1.0 (radiance cache): https://gpuopen.com/download/publications/GPUOpen2022_GI1_0.pdf?utm_source=twitter&utm_medium=social&utm_campaign=arrg
   ReSTIR (reservoir based):
   https://cs.dartmouth.edu/wjarosz/publications/bitterli20spatiotemporal.pdf
   https://d1qx31qr3h6wln.cloudfront.net/publications/ReSTIR%20GI.pdf
   https://d1qx31qr3h6wln.cloudfront.net/publications/sig22_GRIS.pdf

   Lumen (combined SDF + radiance cache?, unsure):
   http://advances.realtimerendering.com/s2022/SIGGRAPH2022-Advances-Lumen-Wright%20et%20al.pdf
   https://www.youtube.com/watch?v=2GYXuM10riw 

   SVGF: https://cg.ivd.kit.edu/publications/2017/svgf/svgf_preprint.pdf 

   DDGI (SDFGI is like 50% DDGI)
   https://morgan3d.github.io/articles/2019-04-01-ddgi/ (scroll down for GDC video)
   https://github.com/morgan3d/articles/blob/main/2019-04-01-ddgi/optimization.html (has some info not on the site)
   Paper/Code: https://jcgt.org/published/0008/02/01/
   Follow up paper: https://arxiv.org/pdf/2009.10796.pdf 
** Filament BDRF
   https://google.github.io/filament/Filament.html#about
** Exposure settings
   https://github.com/bevyengine/bevy/pull/11347
** path guiding
   path guiding方法是一种用于自适应的采样技术，用于快速收敛采样结果，减少噪声。下面是一些参考资料：

   - Real-Time Markov Chain Path Guiding for Global Illumination and Single Scattering
     demo： https://github.com/LDAP/merian-quake
     paper: https://dl.acm.org/doi/10.1145/3728296

   - Markov Chain Mixture Models for Real-Time Direct Illumination
     paper: https://onlinelibrary.wiley.com/doi/10.1111/cgf.14881
     demo: https://github.com/theascone/mcmm-falcor
