[package]
name = "modular_character"
version = "0.1.0"
edition = "2024"

[features]
with-inspector = ["bevy-inspector-egui"]

[dependencies]
bevy = "0.17.0-rc.1"
bevy-inspector-egui = { version = "0.31.0", optional = true }
paste = "1.0"
